### ISSUE TITLE
Build error is thrown when building with SSR (v5.4.0)

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1340]
Ticket ID: 1570101

When upgrading our next.js application to KendoReact ^5.4.0, we receive the following error when building (using SSR).

Downgrading to ~5.1.0 solves the issue.

> Build error occurred
ReferenceError: Element is not defined
    at C:\code\wits-react\src\app\node_modules\@progress\kendo-react-dropdowns\dist\npm\common\DropDownBase.js:226:44
    at Object.<anonymous> (C:\code\wits-react\src\app\node_modules\@progress\kendo-react-dropdowns\dist\npm\common\DropDownBase.js:254:2)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\code\wits-react\src\app\node_modules\@progress\kendo-react-dropdowns\dist\npm\DropDownList\DropDownList.js:38:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  type: 'ReferenceError'
}

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1570367

**Comment by bogdan-craciun** [comment]
Hi, we are having the same issue. Basically we get "Element is not defined" and the app doesn't work at all anymore. I managed to track it down into the AutoComplete component (from '@progress/kendo-react-dropdowns'). I'm attaching a screenshot with what we currently use, if it's any help.

<img width="281" alt="Screenshot 2022-06-27 194313" src="https://user-images.githubusercontent.com/7734486/175992604-5ff7fcf0-e941-4a43-912c-67ab2cdbef3d.png">

**Comment by nstoychev** [comment]
Fixed in our development channel version 5.5.0-dev.202206280851. See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
