### ISSUE TITLE
After upgrade from 6.1.1 to 7.x.x build crashes. 

### ISSUE THREAD

**Issue by bva999** [telerik/kendo-react#1857]
## I'm submitting a...

* Bug report 

## Current behavior
After upgrading to version 7.0.0 and higher it's crushes on build. 

## Expected behavior
It worked fine until version 6.1.1

## Minimal reproduction of the problem with instructions
If I update packages to version 7.0.0 and higher and after I run command gulp serve (SharePoint Framework) I get a lot of errors like this: 
```
`@ ./node_modules/@progress/kendo-react-data-tools/index.js
 @ ./node_modules/@progress/kendo-react-grid/index.mjs
 @ ./lib/controls/TeamRolesControl/TeamRolesControl.js
 @ ./lib/controls/index.js
 @ ./lib/webparts/tenders/components/Main/Tenders.js
 @ ./lib/webparts/tenders/TendersWebPart.js
./node_modules/@progress/kendo-react-dropdowns/index.mjs 1125:17-19
Can't import the named export 'xIcon' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (D:/Projects/PMCG/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (D:/Projects/PMCG/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1463:22)
    at D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1253:28)
    at D:/Projects/PMCG/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:92:22)`
```

```
`@ ./node_modules/@progress/kendo-react-dropdowns/index.js
 @ ./node_modules/@progress/kendo-react-grid/index.mjs
 @ ./lib/controls/TeamRolesControl/TeamRolesControl.js
 @ ./lib/controls/index.js
 @ ./lib/webparts/tenders/components/Main/Tenders.js
 @ ./lib/webparts/tenders/TendersWebPart.js
./node_modules/@progress/kendo-react-grid/index.mjs 3777:0-3823:2
Can't reexport the named export 'getSelectedState' from non EcmaScript module (only default export is available)
    at HarmonyExportImportedSpecifierDependency._getErrors (D:/Projects/PMCG/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:374:6)
    at HarmonyExportImportedSpecifierDependency.getErrors (D:/Projects/PMCG/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:354:16)
    at Compilation.reportDependencyErrorsAndWarnings (D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1463:22)
    at D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1253:28)
    at D:/Projects/PMCG/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:92:22)`
```

```
`@ ./lib/controls/TeamRolesControl/TeamRolesControl.js
 @ ./lib/controls/index.js
 @ ./lib/webparts/tenders/components/Main/Tenders.js
 @ ./lib/webparts/tenders/TendersWebPart.js
./node_modules/@progress/kendo-react-intl/index.mjs 238:0-253:2
Can't reexport the named export 'load' from non EcmaScript module (only default export is available)
    at HarmonyExportImportedSpecifierDependency._getErrors (D:/Projects/PMCG/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:374:6)
    at HarmonyExportImportedSpecifierDependency.getErrors (D:/Projects/PMCG/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:354:16)
    at Compilation.reportDependencyErrorsAndWarnings (D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1463:22)
    at D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (D:/Projects/PMCG/node_modules/webpack/lib/Compilation.js:1253:28)
    at D:/Projects/PMCG/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (D:/Projects/PMCG/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:92:22)`
```
and e.t.c. 

## Environment

Package versions:
7.0.0 - 7.0.2
My packpackage.json
```
{
  "name": "xxx",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=16.13.0 <17.0.0 || >=18.17.1 <19.0.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "serve": "gulp bundle --custom-serve --max_old_space_size=4096 && fast-serve"
  },
  "dependencies": {
    "@dnd-kit/modifiers": "^6.0.1",
    "@dnd-kit/sortable": "^7.0.2",
    "@fluentui-contrib/react-data-grid-react-window": "^1.1.2",
    "@fluentui/react": "^8.109.0",
    "@fluentui/react-components": "^9.37.4",
    "@microsoft/decorators": "1.18.2",
    "@microsoft/sp-adaptive-card-extension-base": "1.18.2",
    "@microsoft/sp-core-library": "1.18.2",
    "@microsoft/sp-http": "1.18.2",
    "@microsoft/sp-listview-extensibility": "1.18.2",
    "@microsoft/sp-lodash-subset": "1.18.2",
    "@microsoft/sp-office-ui-fabric-core": "1.18.2",
    "@microsoft/sp-property-pane": "1.18.2",
    "@microsoft/sp-webpart-base": "1.18.2",
    "@pnp/common": "^2.12.0",
    "@pnp/graph": "^2.12.0",
    "@pnp/logging": "^2.12.0",
    "@pnp/odata": "^2.12.0",
    "@pnp/sp": "^2.12.0",
    "@pnp/spfx-controls-react": "3.16.1",
    "@progress/kendo-data-query": "^1.7.0",
    "@progress/kendo-drawing": "^1.18.0",
    "@progress/kendo-licensing": "^1.3.3",
    "@progress/kendo-react-animation": "^7.0.0",
    "@progress/kendo-react-data-tools": "^7.0.0",
    "@progress/kendo-react-dateinputs": "^7.0.0",
    "@progress/kendo-react-dropdowns": "^7.0.0",
    "@progress/kendo-react-grid": "^7.0.0",
    "@progress/kendo-react-indicators": "^7.0.0",
    "@progress/kendo-react-inputs": "^7.0.0",
    "@progress/kendo-react-intl": "^7.0.0",
    "@progress/kendo-theme-bootstrap": "^7.0.1",
    "@progress/kendo-theme-default": "^7.0.1",
    "@progress/kendo-theme-material": "^7.0.1",
    "@types/file-saver": "^2.0.5",
    "@types/mocha": "^8.2.3",
    "@types/node": "^11.15.54",
    "@types/react-circular-progressbar": "^1.1.0",
    "docxtemplater": "^3.32.3",
    "file-saver": "^2.0.5",
    "html-react-parser": "^4.0.0",
    "memoize-one": "^5.2.1",
    "moment-timezone": "^0.5.38",
    "pizzip": "^3.1.3",
    "react": "17.0.1",
    "react-activity": "^1.2.2",
    "react-big-calendar": "^1.5.2",
    "react-circular-progressbar": "^2.0.4",
    "react-dom": "17.0.1",
    "react-file-reader": "^1.1.4",
    "react-rte": "^0.16.5",
    "react-toastify": "^8.2.0",
    "react-vertical-timeline-component": "^3.3.3",
    "save": "^2.9.0",
    "tslib": "2.3.1",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@iconify/react": "^4.1.1",
    "@microsoft/eslint-config-spfx": "1.18.2",
    "@microsoft/eslint-plugin-spfx": "1.18.2",
    "@microsoft/microsoft-graph-types": "^2.25.0",
    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
    "@microsoft/sp-build-web": "1.18.2",
    "@microsoft/sp-module-interfaces": "1.18.2",
    "@rushstack/eslint-config": "2.5.1",
    "@types/react": "17.0.45",
    "@types/react-big-calendar": "^0.38.2",
    "@types/react-dom": "17.0.17",
    "@types/react-vertical-timeline-component": "^3.3.3",
    "@types/webpack-env": "1.15.2",
    "ajv": "6.12.5",
    "chai": "^4.3.7",
    "cross-env": "7.0.2",
    "css-modules-typescript-loader": "^4.0.1",
    "del": "5.1.0",
    "eslint": "8.7.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "fork-ts-checker-webpack-plugin": "4.1.0",
    "gulp": "~4.0.2",
    "spfx-fast-serve-helpers": "~1.18.0",
    "style-loader": "1.1.3",
    "ts-loader": "^6.2.2",
    "typescript": "4.7.4",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.3"
  },
  "resolutions": {
    "@types/react": "17.0.45"
  }
}

```

Browser:

- Edge version 120.0.2210.121

System:
- TypeScript version: 4.7.4 
- Node version: v18.19.0 
- Platform:  Wndows, Sharepoint Framework 1.18.2

**Comment by vveesseelliinnaa** [comment]
Thanks a lot for the reported problem, @bva999! We will make sure to look at it as soon as possible.

**Comment by tsvetomir** [comment]
There are 2 issues at play here:
* The built-in SharePoint Webpack configuration does not handle the `.mjs` modules that we shipped as part of #1799.

  We could potentially mitigate this on the package side by switching to `"type": "module"` and using `.js` and `.cjs` extensions instead of `.mjs`, but we're not confident this won't break something else.

  The solution for the moment is to [Extend the Webpack configuration](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/extending-webpack-in-build-pipeline) in your `gulpfile.js`:

  ```js
  const build = require('@microsoft/sp-build-web');

  // ...

  build.configureWebpack.mergeConfig({
    additionalConfiguration: (generatedConfiguration) => {
      generatedConfiguration.module.rules.push(
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto'
        }
      );
  
      return generatedConfiguration;
    }
  });

  build.initialize(require('gulp'));
  ```

* SharePoint doesn't currently support ES2020 modules, see https://github.com/SharePoint/sp-dev-docs/issues/8638.

  To fix this, we need to downgrade our bundles to ES2019 which is something we're willing to do to improve compatibility. The current [Development Build](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) (7.0.3-develop.11) already includes this fix. Please, give it a shot and let me know if that works for you.

**Comment by bva999** [comment]
Hi @tsvetomir . Extending the webpack config in gulpfile.js has helped with `.mjs` error. 
But what about the second issue, I've updated to `7.0.3-develop.11` but got errors : 

```
`ERROR in ./node_modules/@progress/kendo-react-treeview/index.mjs 743:0-754:2
Can't reexport the named export 'TreeFieldsService' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/@progress/kendo-react-grid/index.mjs 3777:0-3823:2
Can't reexport the named export 'getSelectedState' from non EcmaScript module (only default export is available)`
```

**Comment by tsvetomir** [comment]
@bva999 this looks like the same issue with Webpack and should be solved by the updated config. Do you get the same error when running just `gulp build`?

I'm attaching my test project as reference: [sp-kendoreact.zip](https://github.com/telerik/kendo-react/files/13936745/sp-kendoreact.zip). I've used the [sp-dev-fx-webparts](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-cascadingdropdowns) samples as a starting point.

**Comment by bva999** [comment]
> @bva999 this looks like the same issue with Webpack and should be solved by the updated config. Do you get the same error when running just `gulp build`?
> 
No , `gulp build` works without errors. 
> I'm attaching my test project as reference: [sp-kendoreact.zip](https://github.com/telerik/kendo-react/files/13936745/sp-kendoreact.zip). I've used the [sp-dev-fx-webparts](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-cascadingdropdowns) samples as a starting point.

'gulp serve --nobrowser' also works without errors, but if I test my webpart it throws an error: 

```
ERROR:
Cannot read properties of undefined (reading 'default')

CALL STACK:
TypeError: Cannot read properties of undefined (reading 'default')
    at 76ZC (https://localhost:4321/dist/projects-web-part.js:52518:20)
    at __webpack_require__ (https://localhost:4321/dist/projects-web-part.js:64:30)
    at 4a3J (https://localhost:4321/dist/projects-web-part.js:38019:67)
    at __webpack_require__ (https://localhost:4321/dist/projects-web-part.js:64:30)
    at 717H (https://localhost:4321/dist/projects-web-part.js:50318:76)
    at __webpack_require__ (https://localhost:4321/dist/projects-web-part.js:64:30)
    at /awB (https://localhost:4321/dist/projects-web-part.js:10463:76)
    at __webpack_require__ (https://localhost:4321/dist/projects-web-part.js:64:30)
    at 5iAl (https://localhost:4321/dist/projects-web-part.js:44985:83)
    at __webpack_require__ (https://localhost:4321/dist/projects-web-part.js:64:30)
```

**Comment by tsvetomir** [comment]
I'll try to debug the`gulp serve` output, but on a first look the bundle seems to include all KendoReact dependencies.

The spfx-fast-serve tool offers [a similar hook](https://github.com/s-KaiNet/spfx-fast-serve#webpack-extensibility) for extending the Webpack configuration. Modify the `transformConfig` method in the generated `fast-serve/webpack.extend.js` as follows:

```js
/**
 * For even more fine-grained control, you can apply custom webpack settings using below function
 * @param {object} initialWebpackConfig - initial webpack config object
 * @param {object} webpack - webpack object, used by SPFx pipeline
 * @returns webpack config object
 */
const transformConfig = function (initialWebpackConfig, webpack) {
  // transform the initial webpack config here, i.e.
  // initialWebpackConfig.plugins.push(new webpack.Plugin()); etc.
  initialWebpackConfig.module.rules.push(
    {
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto'
    }
  );

  return initialWebpackConfig;
}
```

**Comment by tsvetomir** [comment]
Quick update, I was able to load the web part successfully into SharePoint without further modifications.

**Comment by bva999** [comment]
Thank you @tsvetomir. Your advice helped. And solution works fine with the last dev versions.

**Comment by tsvetomir** [comment]
Thanks for the confirmation!

We'll add this to the docs and we'll consider our options for improving the compatibility with SharePoint. 
/cc @vveesseelliinnaa @WissamProgress
