### ISSUE TITLE
Yarn install of kendo package fails with “Registry failed to return tag”

### ISSUE THREAD

**Issue by tuliof** [telerik/kendo-react#871]
## I'm submitting a...

* Bug report

## Current behavior

After updating to yarn V2, running `yarn install` fails with:

> ➤ YN0000: │ UnhandledPromiseRejectionWarning: Error: @progress/kendo-base-component-react-wrapper@npm:2019.2.0606: Registry failed to return tag "2019.2.0606"
    at W.resolvers.getCandidates (C:\dev\DMDS\DMDS.WebApp.Public\.yarn\releases\yarn-2.4.0.cjs:2:232860)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
➤ YN0000: │ UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
➤ YN0000: │ DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The above block repeats 3x 

## Expected behavior

There is no 2019.2.0606 tag listed for [kendo-base-component-react-wrapper](https://yarnpkg.com/package/@progress/kendo-base-component-react-wrapper) on yarnpkg.com, although it does have a 2019.2.606 version listed, notice the mismatched patch number from the log ".0606" against ".606" from the repo.

Expected behavior would be to have that peer dependency met.

## Minimal reproduction of the problem with instructions

I have 3 packages that depends on the one on the error.
 * @progress/kendo-dateinputs-react-wrapper@^2019.2.606
 * @progress/kendo-dropdowns-react-wrapper@^2019.2.606
 * @progress/kendo-editor-react-wrapper@^2019.2.606

Here is my [package.json](https://github.com/telerik/kendo-react/files/6050965/package.json.txt)

## Environment

Package versions:
```
+-- UNMET DEPENDENCY @babel/polyfill@^7.0.0
+-- UNMET DEPENDENCY @progress/kendo-data-query@^1.5.1
+-- UNMET DEPENDENCY @progress/kendo-dateinputs-react-wrapper@^2019.2.606
+-- UNMET DEPENDENCY @progress/kendo-drawing@^1.2.0 ^1.5.12
+-- UNMET DEPENDENCY @progress/kendo-dropdowns-react-wrapper@^2019.2.606
+-- UNMET DEPENDENCY @progress/kendo-editor-react-wrapper@^2019.2.606
+-- UNMET DEPENDENCY @progress/kendo-react-animation@^3.13.0
+-- UNMET DEPENDENCY @progress/kendo-react-buttons@^3.13.0
+-- UNMET DEPENDENCY @progress/kendo-react-data-tools@^3.13.0
+-- UNMET DEPENDENCY @progress/kendo-react-dateinputs@^3.2.2
+-- UNMET DEPENDENCY @progress/kendo-react-dropdowns@^3.2.2
+-- UNMET DEPENDENCY @progress/kendo-react-grid@^3.2.2
+-- UNMET DEPENDENCY @progress/kendo-react-inputs@^3.2.2
+-- UNMET DEPENDENCY @progress/kendo-react-intl@^3.2.2
+-- UNMET DEPENDENCY @progress/kendo-react-layout@^3.2.2
+-- UNMET DEPENDENCY @progress/kendo-react-popup@^3.13.0
+-- UNMET DEPENDENCY @progress/kendo-react-progressbars@^3.13.0
+-- UNMET DEPENDENCY @progress/kendo-theme-default@^4.0.0
+-- UNMET DEPENDENCY @progress/kendo-ui@^2019.2.710
+-- UNMET DEPENDENCY babel-plugin-transform-decorators-legacy@1.3.5
+-- UNMET DEPENDENCY bootstrap@^3.3.1
+-- UNMET DEPENDENCY bootstrap-toggle@^2.2.2
+-- UNMET DEPENDENCY cleave.js@^1.2.1
+-- UNMET DEPENDENCY create-react-class@^15.6.3
+-- UNMET DEPENDENCY cross-fetch@^3.0.0
+-- UNMET DEPENDENCY es6-promise@^4.2.4
+-- UNMET DEPENDENCY file-saver@^2.0.2
+-- UNMET DEPENDENCY fine-uploader@^5.16.2
+-- UNMET DEPENDENCY font-awesome@4.7.0
+-- UNMET DEPENDENCY jquery@^2.1.1
+-- UNMET DEPENDENCY lodash@^4.17.5
+-- UNMET DEPENDENCY moment@^2.20.1
+-- UNMET DEPENDENCY moment-timezone@^0.5.26
+-- UNMET DEPENDENCY prop-types@^15.6.0
+-- UNMET DEPENDENCY react@16.8.6
+-- UNMET DEPENDENCY react-csv@^2.0.3
+-- UNMET DEPENDENCY react-day-picker@^7.4.8
+-- UNMET DEPENDENCY react-dom@16.8.6
+-- UNMET DEPENDENCY react-redux@^6.0.0
+-- UNMET DEPENDENCY redux@^4.0.1
+-- UNMET DEPENDENCY redux-thunk@^2.3.0
+-- UNMET DEPENDENCY reselect@^4.0.0
`-- UNMET DEPENDENCY resize-observer-polyfill@^1.5.0

npm ERR! missing: @babel/polyfill@^7.0.0, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-data-query@^1.5.1, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-dateinputs-react-wrapper@^2019.2.606, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-drawing@^1.2.0 ^1.5.12, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-dropdowns-react-wrapper@^2019.2.606, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-editor-react-wrapper@^2019.2.606, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-animation@^3.13.0, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-buttons@^3.13.0, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-data-tools@^3.13.0, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-dateinputs@^3.2.2, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-dropdowns@^3.2.2, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-grid@^3.2.2, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-inputs@^3.2.2, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-intl@^3.2.2, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-layout@^3.2.2, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-popup@^3.13.0, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-react-progressbars@^3.13.0, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-theme-default@^4.0.0, required by dmds@1.0.0
npm ERR! missing: @progress/kendo-ui@^2019.2.710, required by dmds@1.0.0
npm ERR! missing: babel-plugin-transform-decorators-legacy@1.3.5, required by dmds@1.0.0
npm ERR! missing: bootstrap@^3.3.1, required by dmds@1.0.0
npm ERR! missing: bootstrap-toggle@^2.2.2, required by dmds@1.0.0
npm ERR! missing: cleave.js@^1.2.1, required by dmds@1.0.0
npm ERR! missing: create-react-class@^15.6.3, required by dmds@1.0.0
npm ERR! missing: cross-fetch@^3.0.0, required by dmds@1.0.0
npm ERR! missing: es6-promise@^4.2.4, required by dmds@1.0.0
npm ERR! missing: file-saver@^2.0.2, required by dmds@1.0.0
npm ERR! missing: fine-uploader@^5.16.2, required by dmds@1.0.0
npm ERR! missing: font-awesome@4.7.0, required by dmds@1.0.0
npm ERR! missing: jquery@^2.1.1, required by dmds@1.0.0
npm ERR! missing: lodash@^4.17.5, required by dmds@1.0.0
npm ERR! missing: moment@^2.20.1, required by dmds@1.0.0
npm ERR! missing: moment-timezone@^0.5.26, required by dmds@1.0.0
npm ERR! missing: prop-types@^15.6.0, required by dmds@1.0.0
npm ERR! missing: react@16.8.6, required by dmds@1.0.0
npm ERR! missing: react-csv@^2.0.3, required by dmds@1.0.0
npm ERR! missing: react-day-picker@^7.4.8, required by dmds@1.0.0
npm ERR! missing: react-dom@16.8.6, required by dmds@1.0.0
npm ERR! missing: react-redux@^6.0.0, required by dmds@1.0.0
npm ERR! missing: redux@^4.0.1, required by dmds@1.0.0
npm ERR! missing: redux-thunk@^2.3.0, required by dmds@1.0.0
npm ERR! missing: reselect@^4.0.0, required by dmds@1.0.0
npm ERR! missing: resize-observer-polyfill@^1.5.0, required by dmds@1.0.0
```

System:
- Node version: v11.15.0
- NPM version: 6.14.7
- Yarn version: 2.4.0
   - npmRegistryServer: 'https://registry.yarnpkg.com'
- Platform:  Windows 10

**Comment by Xizario** [comment]
As there are native counterparts for these packages, we don't longer update the wrappers one. If you want to use the jQuery widgets inside a react app the official way is described here: https://docs.telerik.com/kendo-ui/third-party/react

**Comment by tuliof** [comment]
We ended up replacing the react-wrappers with kendo react libs, e.g. `@progress/kendo-react-editor` package.
